spring:
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        implicit-strategy: com.wooming.iotsmarthome.config.jpa.RdbNamingStrategy
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
      hibernate.format_sql: true
      hibernate.show_sql: true
    open-in-view: true
    generate-ddl: true

  datasource:
    url: jdbc:postgresql://localhost:5432/smart_home
    username: wooming
    password: pwd

aws:
  iot:
    mqtt:
      clientEndPoint: <your-client-end-point>
      clientId: <your-client-id>
    iam:
      accessKey: <your-iam-access-key>
      secretKey: <your-iam-secret-key>
