spring:
  jpa:
    hibernate:
      naming:
        implicit-strategy: com.wooming.iotsmarthome.config.jpa.RdbNamingStrategy
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
      hibernate.format_sql: true
      hibernate.show_sql: true
    open-in-view: true
    generate-ddl: true

cloud:
  aws:
    credentials:
      access-key: <your-iam-access-key>
      secret-key: <your-iam-secret-key>
    iot:
      endpoint: <your-client-end-point>
      clientId: <your-client-id>
      region: <your-client-region>
